version: '3.8'

volumes:
  consul-data-leader:
     driver: glusterfs
     name: "data/vol/consul-data-leader" 

  consul-data-replica:
     driver: glusterfs
     name: "data/vol/consul-data-leader"

networks:
  traefik-public:
    external: true

services:
  consul-leader:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - default
      - traefik-public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - "traefik.frontend.rule=Host:consul.umanlogics.com"
        - traefik.enable=true
        - traefik.port=8500
        - "traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}"
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - "traefik.frontend.auth.basic.users=user:$$apr1$$LojRANYP$$FtsMIfeAKHLB43xWw1ofC0"
   
  consul-replica:
    image: consul
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - default
      - traefik-public
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1

  traefik:
    image: traefik:v1.7
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - "traefik.frontend.rule=Host:traefik.umanlogics.com"
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - "traefik.frontend.auth.basic.users=user:$$apr1$$LojRANYP$$FtsMIfeAKHLB43xWw1ofC0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: 
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=false
      --constraints=tag==traefik-public
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --consul
      --consul.endpoint="consul-leader:8500"
      --acme
      --acme.email=v.vanuytven@umanlogics.com
      --acme.storage="traefik/acme/account"
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.onhostrule=true
      --acme.acmelogging=true
      --logLevel=INFO
      --accessLog
      --api
      --metrics
      --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
    networks:
      - default
      - traefik-public
    depends_on:
      - consul-leader
